### ISSUE TITLE
Use tempfile.NamedTemporaryFile

### ISSUE THREAD

**Issue by ashcrow** [coreos/fcct-online#2]
Temporary files are in use in `app.py`. Check to see if using [tempfile](https://docs.python.org/3/library/tempfile.html) could replace manual temporary file usage.

**Comment by zonggen** [comment]
Turns out no tempfiles are needed https://github.com/zonggen/fcct-online/issues/3#issuecomment-518679417. Thanks for the link!

**Comment by ashcrow** [comment]
Since no temp files are needed this issue can be closed.
