### ISSUE TITLE
Check config_string input before use

### ISSUE THREAD

**Issue by ashcrow** [coreos/fcct-online#5]
Before https://github.com/zonggen/fcct-online/blob/master/server/app.py#L36 it's likely a good idea to:

- Ensure the input is JSON
- Is under some max length

**Comment by zonggen** [comment]
That's a good idea. I should add more error handling. Thanks!

**Comment by zonggen** [comment]
Update:
 - Added input type checking (94d7b0c585a4b6f4a309bfb1835baaf5793691f4)
- Added config string length checking (2b91b85278b527ca958e4ec771982e6d29aa9bc1)
