### ISSUE TITLE
Copying transpiled config to clipboard is tricky

### ISSUE THREAD

**Issue by sgreene570** [coreos/fcct-online#9]
The textarea where the generated ignition config is displayed is not paste buffer friendly. 
A triple click inside the text box on chrome does not highlight the entire contents of the textarea, so one has to highlight every line by clicking and dragging. Changing the type of textbox, or alternatively adding a "copy config to clipboard" button would be very useful (or, why not both?).

**Comment by zonggen** [comment]
Thanks for pointing that out!
 - [x] Enable triple click to select whole content (by adding an event listener to textbox)
 - [ ] Adding copy to clipboard button (potentially for both URL and Ignition config)

> Changing the type of textbox

Could you extend a little, what do you mean by _type_ of textbox?

**Comment by sgreene570** [comment]
> Could you extend a little, what do you mean by _type_ of textbox?

Event listener sounds like the way to go, I thought there might have been a sub type of the generic text area that would automatically have the triple click controls configured, but I think I am mistaken.
